services:
  db:
    image: postgres:16-alpine
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: duct-todo-user
      POSTGRES_PASSWORD: duct-todo-pass
      POSTGRES_DB: duct-todo
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
volumes:
  data:

